CREATE TABLE preferences (
    id SERIAL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    w_distance DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    w_price DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);